local opt = vim.opt

opt.winborder = 'rounded'
opt.clipboard = 'unnamedplus'
opt.autocomplete = false
opt.completeopt = { 'popup', 'menu', 'menuone', 'noinsert', 'fuzzy' }
opt.completefuzzycollect = { 'keyword', 'files' }
opt.complete = '.,w^5,b^5,o^5'
opt.pumheight = 5
vim.g.autocompletedelay = 120
vim.g.autocompletetimeout = 120
opt.grepformat = '%f:%l:%c:%m'
opt.grepprg = 'rg --vimgrep --smartcase'
opt.inccommand = 'nosplit'
opt.jumpoptions = 'view'
opt.splitkeep = 'screen'
opt.signcolumn = 'yes'
opt.mouse = 'a'
opt.pumheight = 10
opt.laststatus = 3
opt.scrolloff = 4
opt.sidescrolloff = 8
opt.linebreak = false
opt.list = true
opt.confirm = true
opt.number = true
opt.shiftround = true
opt.relativenumber = false
opt.wrap = false
opt.tabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.smartindent = true
opt.cursorline = true
opt.splitbelow = true
opt.undofile = false
opt.splitright = true
opt.ignorecase = true
opt.smartcase = true
opt.virtualedit = 'block'
opt.winminwidth = 5
opt.smoothscroll = true
opt.updatetime = 500
